name: Daily Automation Tasks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Profile 3D 图像更新（每天 5:00 UTC）
    - cron: "0 21 * * *"

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    name: Generate README
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: 设置时区
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Shanghai'
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "Asia/Shanghai"

      - name: 环境配置
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: 缓存
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: 安装依赖
        run: npm install

      - name: 生成 README.md
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          USERNAME: ${{ secrets.USERNAME }}
          GO_EMAIL: ${{ secrets.GO_EMAIL }}
        run: npm run build --if-present

      - name: Git Pull Before Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase --autostash origin main

      - name: 推送新 README.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update README"
          branch: main
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com